import { v4 as uuid } from 'uuid';
import { smartphonesIds } from './05-shop-products';
import {
  orderForUserWithCartItemsAndOrdersAndReviewsProcessing,
  orderForUserWithCartItemsAndOrdersAndReviewsCanceled,
  orderForUserWithCartItemsAndOrdersAndReviewsDelivered,
  orderedProductWithAddon,
  orderedProductThreeStars,
  orderedProductFourStars,
  userWithCartItemsAndOrdersAndReviews,
  secondUserWithAReview,
  orderForSecondUserWithAReview,
  orderForThirdUserWithAReview,
  thirdUserWithAReview,
  orderForFourthUserWithAReview,
  fourthUserWithAReview,
  orderedProductForSecondUser,
  orderedProductForThirdUser,
  orderedProductForFourthUser,
  cartForUserWithCartItemsAndOrderAndReviews,
  cartForSecondUserWithReviews,
  cartForThirdUserWithReviews,
  cartForFourthUserWithReviews,
  cartForUserWithCartItemsAndSavedAddresses,
  userWithCartItemsAndSavedAddresses,
  orderForUserWhoCanWriteReviews,
  userWhoCanWriteReviews,
} from '../utils/consts';
import { apple, samsung } from './03-brands';
import { smartphone } from './04-types';

export default {
  up: async (queryInterface) => queryInterface.bulkInsert('OrderedProduct', [
    {
      price: 80000,
      cartId: cartForUserWithCartItemsAndSavedAddresses,
      brandId: samsung,
      typeId: smartphone,
      userId: userWithCartItemsAndSavedAddresses,
      shopProductId: smartphonesIds[0],
      id: uuid(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 80000,
      cartId: cartForUserWithCartItemsAndSavedAddresses,
      brandId: samsung,
      typeId: smartphone,
      userId: userWithCartItemsAndSavedAddresses,
      shopProductId: smartphonesIds[0],
      id: uuid(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 80000,
      cartId: cartForUserWithCartItemsAndOrderAndReviews,
      orderId: orderForUserWithCartItemsAndOrdersAndReviewsProcessing,
      brandId: samsung,
      typeId: smartphone,
      userId: userWithCartItemsAndOrdersAndReviews,
      shopProductId: smartphonesIds[0],
      id: uuid(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 80000,
      cartId: cartForUserWithCartItemsAndOrderAndReviews,
      orderId: orderForUserWithCartItemsAndOrdersAndReviewsCanceled,
      brandId: samsung,
      typeId: smartphone,
      userId: userWithCartItemsAndOrdersAndReviews,
      shopProductId: smartphonesIds[0],
      id: uuid(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 80000,
      cartId: cartForUserWithCartItemsAndOrderAndReviews,
      orderId: orderForUserWithCartItemsAndOrdersAndReviewsDelivered,
      brandId: samsung,
      typeId: smartphone,
      userId: userWithCartItemsAndOrdersAndReviews,
      shopProductId: smartphonesIds[0],
      id: orderedProductWithAddon,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 80000,
      cartId: cartForUserWithCartItemsAndOrderAndReviews,
      orderId: orderForUserWithCartItemsAndOrdersAndReviewsDelivered,
      brandId: apple,
      typeId: smartphone,
      userId: userWithCartItemsAndOrdersAndReviews,
      shopProductId: smartphonesIds[3],
      id: orderedProductThreeStars,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 80000,
      cartId: cartForUserWithCartItemsAndOrderAndReviews,
      orderId: orderForUserWithCartItemsAndOrdersAndReviewsDelivered,
      brandId: apple,
      typeId: smartphone,
      userId: userWithCartItemsAndOrdersAndReviews,
      shopProductId: smartphonesIds[3],
      id: orderedProductFourStars,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 80000,
      orderId: orderForSecondUserWithAReview,
      cartId: cartForSecondUserWithReviews,
      brandId: samsung,
      typeId: smartphone,
      userId: secondUserWithAReview,
      shopProductId: smartphonesIds[0],
      id: orderedProductForSecondUser,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 80000,
      orderId: orderForThirdUserWithAReview,
      cartId: cartForThirdUserWithReviews,
      brandId: samsung,
      typeId: smartphone,
      userId: thirdUserWithAReview,
      shopProductId: smartphonesIds[0],
      id: orderedProductForThirdUser,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 80000,
      orderId: orderForFourthUserWithAReview,
      cartId: cartForFourthUserWithReviews,
      brandId: samsung,
      typeId: smartphone,
      userId: fourthUserWithAReview,
      shopProductId: smartphonesIds[0],
      id: orderedProductForFourthUser,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 80000,
      orderId: orderForUserWhoCanWriteReviews,
      brandId: samsung,
      typeId: smartphone,
      userId: userWhoCanWriteReviews,
      shopProductId: smartphonesIds[0],
      id: uuid(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 80000,
      orderId: orderForUserWhoCanWriteReviews,
      brandId: samsung,
      typeId: smartphone,
      userId: userWhoCanWriteReviews,
      shopProductId: smartphonesIds[1],
      id: uuid(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]),
  down: (queryInterface) => queryInterface.bulkDelete('OrderedProduct', null, {}),
};
