import { v4 as uuid } from 'uuid';
import {
  userWithCartItemsAndSavedAddresses,
  userWithSavedAddresses,
} from '../utils/consts';

export default {
  up: (queryInterface) => queryInterface.bulkInsert('AddressInAddressBook', [
    {
      id: uuid(),
      userId: userWithSavedAddresses,
      firstName: 'Kelsea',
      lastName: 'Sullivan',
      addressLineOne: '5353 Connecticut Avenue NW',
      city: 'Washington',
      state: 'DC',
      zip: '20008',
      isDefault: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: uuid(),
      userId: userWithSavedAddresses,
      firstName: 'Kelsea',
      lastName: 'Sullivan',
      addressLineOne: '8585 Wisconsin Avenue NW',
      addressLineTwo: '#205',
      city: 'Washington',
      state: 'DC',
      zip: '20008',
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: uuid(),
      userId: userWithSavedAddresses,
      firstName: 'Kelsea',
      lastName: 'Sullivan',
      addressLineOne: '2094 Yuma Street NW',
      city: 'Washington',
      state: 'DC',
      zip: '20008',
      isDefault: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: uuid(),
      userId: userWithCartItemsAndSavedAddresses,
      firstName: 'Emmanuella',
      lastName: 'Pedro',
      addressLineOne: '8 Circle Street',
      city: 'Washington',
      state: 'DC',
      zip: '20529',
      isDefault: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: uuid(),
      userId: userWithCartItemsAndSavedAddresses,
      firstName: 'Emmanuella',
      lastName: 'Pedro',
      addressLineOne: '68 Roosevelt Dr.',
      city: 'Washington',
      state: 'DC',
      zip: '20407',
      isDefault: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]),
  down: (queryInterface) => queryInterface.bulkDelete('AddressInAddressBook', null, {}),
};
