import { v4 as uuid } from 'uuid';
import { smartphonesIds } from './05-shop-products';
import {
  orderForUserWithCartItemsAndOrdersAndReviewsProcessing,
  orderForUserWithCartItemsAndOrdersAndReviewsCanceled,
  orderForUserWithCartItemsAndOrdersAndReviewsDelivered,
  orderedProductWithAddon,
  orderedProductThreeStars,
  orderedProductFourStars,
  userWithCartItemsAndOrdersAndReviews,
  secondUserWithAReview,
  orderForSecondUserWithAReview,
  orderForThirdUserWithAReview,
  thirdUserWithAReview,
  orderForFourthUserWithAReview,
  fourthUserWithAReview,
} from '../utils/consts';
import { apple, samsung } from './03-brands';
import { smartphone } from './04-types';

export default {
  up: async (queryInterface) => queryInterface.bulkInsert('OrderedProduct', [
    {
      price: 8000,
      orderId: orderForUserWithCartItemsAndOrdersAndReviewsProcessing,
      brandId: samsung,
      typeId: smartphone,
      userId: userWithCartItemsAndOrdersAndReviews,
      shopProductId: smartphonesIds[0],
      id: uuid(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 8000,
      orderId: orderForUserWithCartItemsAndOrdersAndReviewsCanceled,
      brandId: samsung,
      typeId: smartphone,
      userId: userWithCartItemsAndOrdersAndReviews,
      shopProductId: smartphonesIds[0],
      id: uuid(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 8000,
      orderId: orderForUserWithCartItemsAndOrdersAndReviewsDelivered,
      brandId: samsung,
      typeId: smartphone,
      userId: userWithCartItemsAndOrdersAndReviews,
      shopProductId: smartphonesIds[0],
      id: orderedProductWithAddon,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 8000,
      orderId: orderForUserWithCartItemsAndOrdersAndReviewsDelivered,
      brandId: apple,
      typeId: smartphone,
      userId: userWithCartItemsAndOrdersAndReviews,
      shopProductId: smartphonesIds[3],
      id: orderedProductThreeStars,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 8000,
      orderId: orderForUserWithCartItemsAndOrdersAndReviewsDelivered,
      brandId: apple,
      typeId: smartphone,
      userId: userWithCartItemsAndOrdersAndReviews,
      shopProductId: smartphonesIds[3],
      id: orderedProductFourStars,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 8000,
      orderId: orderForSecondUserWithAReview,
      brandId: samsung,
      typeId: smartphone,
      userId: secondUserWithAReview,
      shopProductId: smartphonesIds[0],
      id: uuid(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 8000,
      orderId: orderForThirdUserWithAReview,
      brandId: samsung,
      typeId: smartphone,
      userId: thirdUserWithAReview,
      shopProductId: smartphonesIds[0],
      id: uuid(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      price: 8000,
      orderId: orderForFourthUserWithAReview,
      brandId: samsung,
      typeId: smartphone,
      userId: fourthUserWithAReview,
      shopProductId: smartphonesIds[0],
      id: uuid(),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]),
  down: (queryInterface) => queryInterface.bulkDelete('OrderedProduct', null, {}),
};
