import { v4 as uuid } from 'uuid';
import {
  orderForUserWithCartItemsAndOrdersAndReviewsProcessing,
  orderForUserWithCartItemsAndOrdersAndReviewsCanceled,
  orderForUserWithCartItemsAndOrdersAndReviewsDelivered,
  orderForFourthUserWithAReview,
  orderForThirdUserWithAReview,
  orderForSecondUserWithAReview,
} from '../utils/consts';

export default {
  up: (queryInterface) => queryInterface.bulkInsert('AddressForOrder', [
    {
      id: uuid(),
      orderId: orderForUserWithCartItemsAndOrdersAndReviewsProcessing,
      firstName: 'Mccauley',
      lastName: 'Gibbons',
      addressLineOne: '8585 Wisconsin Avenue NW',
      addressLineTwo: '#205',
      city: 'Washington',
      state: 'DC',
      zip: '20008',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: uuid(),
      orderId: orderForUserWithCartItemsAndOrdersAndReviewsCanceled,
      firstName: 'Mccauley',
      lastName: 'Gibbons',
      addressLineOne: '8585 Wisconsin Avenue NW',
      addressLineTwo: '#205',
      city: 'Washington',
      state: 'DC',
      zip: '20008',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: uuid(),
      orderId: orderForUserWithCartItemsAndOrdersAndReviewsDelivered,
      firstName: 'Mccauley',
      lastName: 'Gibbons',
      addressLineOne: '8585 Wisconsin Avenue NW',
      addressLineTwo: '#205',
      city: 'Washington',
      state: 'DC',
      zip: '20008',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: uuid(),
      orderId: orderForSecondUserWithAReview,
      firstName: 'Eveleen',
      lastName: 'Andriy',
      addressLineOne: '5555 Wisconsin Ave',
      addressLineTwo: '',
      city: 'Chevy Chase',
      state: 'MD',
      zip: '20815',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: uuid(),
      orderId: orderForThirdUserWithAReview,
      firstName: 'Kristopher',
      lastName: 'Gu',
      addressLineOne: '5500 Connecticut Ave NW',
      addressLineTwo: '',
      city: 'Washington',
      state: 'DC',
      zip: '20015',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: uuid(),
      orderId: orderForFourthUserWithAReview,
      firstName: 'Asmara',
      lastName: 'Permatasari',
      addressLineOne: '3100 14th St NW Ste 201',
      addressLineTwo: 'Ste 201',
      city: 'Washington',
      state: 'DC',
      zip: '20010',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]),
  down: (queryInterface) => queryInterface.bulkDelete('AddressForOrder', null, {}),
};
